import type { Metadata } from "next";
import { bricolage, jetbrainsMono, sfPro } from "./fonts";
import "remixicon/fonts/remixicon.css";
import "./globals.css";
import Footer from "@/components/layout/Footer/Footer";
import ProHeader from "@/components/layout/ProHeader/ProHeader";
import { LenisProvider } from "@/components/providers/lenis-provider";
import { cn } from "@/lib/utils";
import "lenis/dist/lenis.css";
import Providers from "@/libs/ReduxProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn(
        bricolage.variable,
        jetbrainsMono.variable,
        sfPro.className,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col">
        {/* <Header /> */}

        <Providers>
          {/* <ProHeader /> */}
          <LenisProvider>
            {children}
            <Toaster />
          </LenisProvider>
          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  );
}
