import type { Metadata } from "next";
import { bricolage, jetbrainsMono, sfPro } from "./fonts";
import "remixicon/fonts/remixicon.css";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/Footer";
import ProHeader from "@/components/layout/ProHeader/ProHeader";
import { cn } from "@/lib/utils";
import "lenis/dist/lenis.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn(
        bricolage.variable,
        jetbrainsMono.variable,
        sfPro.className,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col">
        {/* <Header /> */}
        <ProHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
